name: walletconnect_mono_auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  pointycastle: ^3.6.2
  walletconnect_mono_core: ^1.0.0
  walletconnect_mono_foundation: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.23.1
