name: walletconnect_mono_foundation
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  convert: ^3.1.1
  cryptography: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  stack_trace: ^1.11.0
  tuple: ^2.0.1
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  lints: ^2.0.1
  test: ^1.23.1

