name: walletconnect_mono_foundation
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  convert: ^3.1.0
  cryptography: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  stack_trace: ^1.10.0
  tuple: ^2.0.1
  web_socket_channel: 2.2.0

dependency_overrides:
  web_socket_channel:
    git:
      url: https://github.com/iota9star/web_socket_channel.git
      ref: fff3297
  build_runner: any

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.4
  freezed: ^2.2.0
  lints: ^2.0.1
  test: ^1.21.4

